# Generated by Django 4.1.2 on 2022-10-10 14:58

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
