# Generated by Django 4.1.2 on 2022-10-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_workouts_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workouts',
            options={'ordering': ['workout_name']},
        ),
        migrations.RenameField(
            model_name='workouts',
            old_name='workout',
            new_name='workout_name',
        ),
    ]
