# Generated by Django 4.1.2 on 2022-10-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_workouts_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveBigIntegerField()),
                ('reps', models.PositiveBigIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('notes', models.CharField(max_length=500)),
                ('performed', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='main_app.workouts')),
            ],
        ),
    ]
