# Generated by Django 4.1.2 on 2022-10-10 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_exercises_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='main_app.workouts'),
        ),
    ]
